homeassistant: true
mqtt:
  base_topic: zigbee2mqtt
  user: addons
  password: leush4engiodoHeiDuBohf6vaevo9sheiQu6rahngaez2oDe8upheiwe5ee4sich
  server: mqtt://core-mosquitto:1883
serial:
  port: /dev/ttyUSB0
frontend:
  port: 8099
advanced:
  log_level: info
  pan_id: 6499
  channel: 15
  network_key:
    - 4
    - 6
    - 3
    - 9
    - 10
    - 11
    - 12
    - 14
    - 0
    - 2
    - 4
    - 6
    - 8
    - 10
    - 12
    - 13
  availability_blocklist: []
  availability_passlist: []
  last_seen: ISO_8601
  homeassistant_legacy_entity_attributes: false
  legacy_api: false
  legacy_availability_payload: false
device_options:
  legacy: false
devices:
  '0x00124b0023ae464d':
    friendly_name: '0x00124b0023ae464d'
  '0x00124b00231ff227':
    friendly_name: '0x00124b00231ff227'
  '0x00124b002265ba65':
    friendly_name: '0x00124b002265ba65'
  '0x086bd7fffe3f4a24':
    friendly_name: '0x086bd7fffe3f4a24'
  '0x003c84fffebb7d2f':
    friendly_name: '0x003c84fffebb7d2f'
  '0xa4c138940f10d76d':
    friendly_name: '0xa4c138940f10d76d'
external_converters:
  - _TZE200_eaac7dkw.js
availability: true
groups: {}
